version: "3.7"

services:
  vscode:
    build: .
    volumes:
      - ../:/go/src/github.com/mrcrilly/goawx
      # (only for debug)
      # - ~/repos-ansible/github/plumbing:/go/src/github.com/nolte/plumbing:cached
      - ~/.ssh:/home/vscode/.ssh:ro
      - ~/.ssh:/root/.ssh:ro
      - /var/run/docker.sock:/var/run/docker.sock
      ## reuse volumes for extensions
      - golang-awx-vol:/home/vscode/.vscode-server/extensions
      # And/or for VS Code Insiders
      - golang-awx-vol-insiders:/home/vscode/.vscode-server-insiders/extensions
    environment:
      - TZ=Europe/Berlin # $(cat /etc/timezone)
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    entrypoint: zsh -c "while sleep 1000; do :; done"
    network_mode: "host"

volumes:
  golang-awx-vol:
  golang-awx-vol-insiders:
